[package]
name = "dune"
version = "0.1.0"
authors = ["Alex Coats <alexandcoats@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4.0"
ron = "0.6.4"
serde = { version = "1.0", features = ["serde_derive"] }
rand = "0.8.0"
ncollide3d = "0.27.0"
maplit = "1.0.2"
laminar = "0.4.0"
rkyv = { version = "0.3.0", features = ["validation"] }
bytecheck = "0.3.0"