[package]
name = "dune"
version = "0.1.0"
authors = ["Alex Coats <alexandcoats@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4.0"
ron = "0.6.4"
serde = { version = "1.0", features = ["serde_derive"] }
rand = "0.8.0"
collision = "0.20.1"
cgmath = "0.17.0"